print('---------GERADOR DE CURRÍCULOS---------')
nome = str(input('Nome completo: '))
ano = int(input('Ano de Nascimento: '))
prof = str(input('Sua profissão: '))
end = str(input('Seu endereço: '))
fone = str(input('Seu telefone: '))
email = str(input('Seu email: '))
curso1 = str(input('Digite um curso: '))
escola1 = str(input('Onde você fez o 1º Curso?'))
duracao1 = str(input('Duração do primeiro curso(em horas/aula): '))
curso2 = str(input('Digite outro curso: '))
escola2 = str(input('Onde você fez o 2º Curso?'))
duracao2 = str(input('Duração do segundo curso(em horas/aula): '))
#geração de curriculo
print('\n')
print('\033[36m//////////////////DADOS PESSOAIS//////////////////')
print('\033[34mNOME: {}'.format(nome.upper()))
if 2018-ano < 18:
    print('{} ANOS - ESTAGIÁRIO'.format(2018-ano))
else:
    print('{} ANOS'.format(2018-ano))
print('PROFISSÃO: {}'.format(prof.upper()))
print('Reside em {}'.format(end))
print('Telefone: {}  /  Email: {}\n\n'.format(fone, email))
print('\033[36m////////////////////////CURSOS////////////////////////')
print('\033[34m{} | {} | Duração: {} horas/aula'.format(curso1,escola1,duracao1))
print('{} | {} | Duração: {} horas/aula'.format(curso2, escola2, duracao2))
